#!/bin/bash
#
# Entrypoint for the wg-client container. Sets up a WireGuard tunnel to the
# mitmproxy container and configures iptables to enforce it. Other containers
# share this network namespace via network_mode: "service:wg-client" and
# inherit the tunnel without needing NET_ADMIN themselves.
#
# Expects:
#   - /mitmproxy-config volume mounted (shared with the mitmproxy container)
#   - NET_ADMIN capability (for creating the WireGuard interface and iptables)
#   - net.ipv4.conf.all.src_valid_mark=1 sysctl (set via docker-compose)
#

WG_JSON="/mitmproxy-config/wireguard.conf"
DNS_CONF="/mitmproxy-config/dns.conf"
DEFAULT_NAMESERVERS=("1.1.1.1" "8.8.8.8")
DNSMASQ_CONF="/etc/dnsmasq-sandcat.conf"
# Sibling containers share wg-client's network namespace via network_mode but
# get their own /etc/resolv.conf in their own mount namespace, so they don't
# inherit the resolv.conf this script writes for wg-client. We publish it here
# for sibling app-init scripts to copy into their own /etc/resolv.conf.
SHARED_RESOLV_CONF="/run/sandcat/resolv.conf"

# Poll a command until it returns success or a timeout is hit.
#
# Args:
#   $1     - max iterations
#   $2     - sleep seconds between iterations
#   $3     - failure message printed to stderr if the command never succeeds
#   $4..$N - command (and args) to run on each iteration
wait_until() {
    local max="$1" delay="$2" msg="$3"
    shift 3
    local attempt=0
    while ! "$@"; do
        if [[ "$attempt" -ge "$max" ]]; then
            echo "$msg" >&2
            return 1
        fi
        sleep "$delay"
        attempt=$((attempt + 1))
    done
}

# Print the upstream nameservers (one per line) the local dnsmasq should
# forward "external" queries to: from $1 (dns.conf written by the addon) when
# present and non-empty, else falling back to the hardcoded defaults.
read_upstream_nameservers() {
    local dns_conf="$1"
    local lines=()
    if [[ -f "$dns_conf" && -s "$dns_conf" ]]; then
        local line
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ -n "$line" ]] && lines+=("$line")
        done < "$dns_conf"
    fi
    [[ "${#lines[@]}" -eq 0 ]] && lines=("${DEFAULT_NAMESERVERS[@]}")
    printf '%s\n' "${lines[@]}"
}

# Print the search domains found in $1 (a resolv.conf-format file), one per
# line. Used to capture the Docker compose project's default network domain
# from the original resolv.conf so we can route those queries to Docker's
# embedded DNS at 127.0.0.11.
extract_search_domains() {
    local resolv_conf="$1"
    [[ -f "$resolv_conf" ]] || return 0
    awk '/^[[:space:]]*search[[:space:]]/ { for (i=2; i<=NF; i++) print $i }' \
        "$resolv_conf"
}

# Write a dnsmasq config that splits DNS:
#  - queries under any of the given search domains (the Docker compose project
#    network) are forwarded to Docker's embedded DNS at 127.0.0.11,
#  - everything else is forwarded to the upstream from dns.conf or defaults.
#
# Args:
#   $1     - path to dns.conf (sidecar from mitmproxy)
#   $2     - path to dnsmasq config to write
#   $3..$N - search domains routed to 127.0.0.11 (may be empty)
write_dnsmasq_conf() {
    local dns_conf="$1"
    local out="$2"
    shift 2

    {
        echo "# Auto-generated by wg-client-init.sh — do not edit."
        echo "no-resolv"
        echo "no-hosts"
        echo "listen-address=127.0.0.1"
        echo "bind-interfaces"
        echo "log-facility=-"
        echo "cache-size=1000"
        # Drop dotless and RFC1918-reverse queries instead of forwarding them.
        # Sibling-container resolution relies on libc expanding bare names via
        # the search domain into FQDNs; any single-label query that still
        # reaches dnsmasq has bypassed that path and shouldn't leak upstream.
        echo "domain-needed"
        echo "bogus-priv"
        local d
        for d in "$@"; do
            printf 'server=/%s/127.0.0.11\n' "$d"
        done
        local ns
        while IFS= read -r ns; do
            printf 'server=%s\n' "$ns"
        done < <(read_upstream_nameservers "$dns_conf")
    } > "$out"
}

# Write a resolv.conf that routes all queries through the local dnsmasq.
# Search domains are preserved so that bare hostnames (e.g. another compose
# service) get expanded by the libc resolver and routed to 127.0.0.11 by
# dnsmasq's `server=/<search>/127.0.0.11` rules.
#
# `options ndots:0` from the Docker-supplied resolv.conf is intentionally NOT
# preserved — it would defeat the search-domain expansion path that lets
# dnsmasq distinguish sibling-container queries from external ones.
#
# Args:
#   $1     - path to resolv.conf to overwrite
#   $2..$N - search domains preserved from the original file (may be empty)
write_resolv_conf() {
    local resolv_conf="$1"
    shift

    {
        echo "nameserver 127.0.0.1"
        if [[ "$#" -gt 0 ]]; then echo "search $*"; fi
    } > "$resolv_conf"
}

main() {
    # Production behavior is errexit; kept inside main() so sourcing the file
    # (e.g. from bats tests) doesn't enable errexit in the caller's shell.
    set -e

    # ── Wait for mitmproxy to be ready ──────────────────────────────────────────
    # The mitmproxy container generates wireguard.conf (key pairs) on startup.
    # The docker-compose healthcheck gates us, but wait just in case.
    wait_until 60 1 \
        "Timed out waiting for mitmproxy wireguard.conf" \
        test -f "$WG_JSON"

    # ── Snapshot search domains BEFORE we overwrite resolv.conf ────────────────
    # Docker populates the container's resolv.conf with the compose project's
    # default network as a search domain. We preserve it so single-label
    # sibling-container lookups still work after dnsmasq takes over.
    local search_domains=()
    mapfile -t search_domains < <(extract_search_domains /etc/resolv.conf)

    # ── Derive WireGuard keys ───────────────────────────────────────────────────
    # mitmproxy stores its WireGuard key pairs as JSON:
    #   {"server_key": "<server-private>", "client_key": "<client-private>"}
    # We need the client's private key and the server's public key (derived from
    # the server's private key).
    local client_private_key server_private_key server_public_key mitmproxy_ip
    client_private_key=$(jq -r .client_key "$WG_JSON")
    server_private_key=$(jq -r .server_key "$WG_JSON")
    server_public_key=$(echo "$server_private_key" | wg pubkey)

    # Resolve the mitmproxy endpoint IP before setting up the tunnel, since DNS
    # won't be available through the normal path after routing is configured.
    mitmproxy_ip=$(getent hosts mitmproxy | awk '{print $1}')

    # ── Create WireGuard interface ──────────────────────────────────────────────
    # We set up WireGuard manually instead of using wg-quick because wg-quick
    # calls `sysctl -w net.ipv4.conf.all.src_valid_mark=1` which fails in Docker
    # (/proc/sys is read-only). The equivalent sysctl is pre-set via the
    # docker-compose `sysctls` option.
    ip link add wg0 type wireguard

    wg set wg0 \
        private-key <(echo "$client_private_key") \
        fwmark 51820 \
        peer "$server_public_key" \
            endpoint mitmproxy:51820 \
            allowed-ips 0.0.0.0/0,::/0

    ip address add 10.0.0.1/32 dev wg0
    ip link set mtu 1420 up dev wg0

    # ── Policy routing ──────────────────────────────────────────────────────────
    # All traffic is routed through wg0 via a custom routing table (51820).
    # WireGuard marks its own encapsulated UDP packets with fwmark 51820, which
    # exempts them from the custom table — so they use the normal default route to
    # reach the mitmproxy endpoint. The suppress_prefixlength rule ensures that
    # local/link-local routes in the main table still work (e.g. Docker DNS,
    # container-to-container traffic).
    ip -4 route add 0.0.0.0/0 dev wg0 table 51820
    ip -4 rule add not fwmark 51820 table 51820
    ip -4 rule add table main suppress_prefixlength 0
    ip -6 route add ::/0 dev wg0 table 51820
    ip -6 rule add not fwmark 51820 table 51820
    ip -6 rule add table main suppress_prefixlength 0

    # ── Firewall kill switch ────────────────────────────────────────────────────
    # iptables rules that enforce the tunnel. Without these, traffic could leak
    # via eth0 if the WireGuard interface goes down, or a process could reach
    # arbitrary IPs on the Docker network subnet directly (bypassing mitmproxy).
    #
    # Installed BEFORE dnsmasq starts so there is no window in which the
    # forwarder could send a query out via eth0 instead of wg0.
    #
    # Insert rules (-I) are evaluated first (in reverse insertion order):
    #   - All traffic on the WireGuard interface (wg0) and loopback
    #   - WireGuard's own UDP encapsulation to the mitmproxy endpoint (fwmark 51820)
    #   - Established/related return traffic on eth0 (for the WG handshake)
    #
    # Append rules (-A) handle remaining eth0 traffic in order:
    #   1. DROP direct access to the mitmproxy container (prevent proxy bypass)
    #   2. DROP access to the Docker gateway (host machine)
    #   3. ACCEPT traffic to other containers on the Docker network
    #   4. DROP everything else (external IPs)
    #
    # These rules cannot be modified by containers sharing this network namespace
    # via network_mode, because those containers don't have NET_ADMIN.
    local docker_network docker_gateway
    docker_network=$(ip -4 route show dev eth0 proto kernel | awk '{print $1}')
    docker_gateway=$(ip -4 route show default dev eth0 | awk '{print $3}')

    if [[ -z "$docker_network" || -z "$docker_gateway" ]]; then
        echo "Failed to determine Docker IPv4 network/gateway for eth0; refusing to configure iptables." >&2
        exit 1
    fi

    iptables -I OUTPUT -o wg0 -j ACCEPT
    iptables -I OUTPUT -o lo -j ACCEPT
    iptables -I OUTPUT -d "$mitmproxy_ip" -p udp --dport 51820 -m mark --mark 51820 -j ACCEPT
    iptables -I OUTPUT -o eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    iptables -A OUTPUT -o eth0 -d "$mitmproxy_ip" -j DROP
    iptables -A OUTPUT -o eth0 -d "$docker_gateway" -j DROP
    iptables -A OUTPUT -o eth0 -d "$docker_network" -j ACCEPT
    iptables -A OUTPUT -o eth0 -j DROP

    ip6tables -I OUTPUT -o wg0 -j ACCEPT
    ip6tables -I OUTPUT -o lo -j ACCEPT
    ip6tables -I OUTPUT -o eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

    local docker_network_v6 docker_gateway_v6
    docker_network_v6=$(ip -6 route show dev eth0 proto kernel 2>/dev/null | awk '{print $1}')
    if [[ -n "$docker_network_v6" ]]; then
        docker_gateway_v6=$(ip -6 route show default dev eth0 2>/dev/null | awk '{print $3}')
        ip6tables -A OUTPUT -o eth0 -d "$mitmproxy_ip" -j DROP
        [[ -n "$docker_gateway_v6" ]] && ip6tables -A OUTPUT -o eth0 -d "$docker_gateway_v6" -j DROP
        ip6tables -A OUTPUT -o eth0 -d "$docker_network_v6" -j ACCEPT
    fi
    ip6tables -A OUTPUT -o eth0 -j DROP

    # ── Local DNS forwarder ────────────────────────────────────────────────────
    # Run dnsmasq on 127.0.0.1 so:
    #  - sibling-container queries (matched via the compose project's search
    #    domain) go to Docker's embedded resolver at 127.0.0.11 (loopback,
    #    NAT'd to the daemon — never enters wg0),
    #  - everything else goes to the upstream from dns.conf (or defaults),
    #    which routes through wg0 → mitmproxy for inspection and policy.
    #
    # Outbound from dnsmasq stays inside the kill-switch installed above:
    #   - 127.0.0.11 traffic uses the lo interface (ACCEPT-ed),
    #   - upstream queries go via wg0 (ACCEPT-ed).
    write_dnsmasq_conf "$DNS_CONF" "$DNSMASQ_CONF" "${search_domains[@]}"
    dnsmasq --conf-file="$DNSMASQ_CONF"

    # dnsmasq daemonizes after parsing its config; verify it actually bound
    # to 127.0.0.1:53 before we point /etc/resolv.conf at it. Without this
    # check, a post-fork crash would silently black-hole every DNS query.
    wait_until 25 0.2 \
        "dnsmasq did not start listening on 127.0.0.1:53" \
        dnsmasq-ready

    write_resolv_conf /etc/resolv.conf "${search_domains[@]}"

    # Publish the same resolv.conf for sibling containers to copy from.
    # See SHARED_RESOLV_CONF declaration for why this is necessary.
    mkdir -p "$(dirname "$SHARED_RESOLV_CONF")"
    write_resolv_conf "$SHARED_RESOLV_CONF" "${search_domains[@]}"

    # Signal readiness to containers waiting on the healthcheck.
    touch /tmp/wg-ready

    supervise_dnsmasq "$DNSMASQ_CONF"
}

# Keep dnsmasq alive in-place. Sibling containers share this container's
# network namespace via `network_mode: service:wg-client`; that binding is
# resolved at sibling-create time, so a wg-client container restart would
# leave the agent attached to a now-destroyed namespace. Supervising dnsmasq
# locally — instead of letting the container exit and rely on Docker's
# restart policy — keeps the namespace intact across dnsmasq crashes.
supervise_dnsmasq() {
    local conf="$1"
    while true; do
        sleep 5
        if ! dnsmasq-ready; then
            echo "[wg-client] dnsmasq not listening; restarting" >&2
            dnsmasq --conf-file="$conf" || true
        fi
    done
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
    main "$@"
fi
